---
title: "Lecture Example"
subtitle: "Lorem Ipsum, dolor sit amet"
author: [John Doe]
keywords: [Markdown]
book: true
date: "\\today"
lang: "it"

# PDF: copertina
titlepage: true
titlepage-color: "154C79"
titlepage-text-color: "154C79"
titlepage-background: "./assets/background.pdf"
titlepage-rule-height: 0

# table of contents
toc-own-page: true

# numerazione primo capitolo
first-chapter: 0


header-includes:
- |
  ```{=latex}
  \usepackage{tcolorbox}

  \newtcolorbox{info-box}{colback=cyan!5!white,colframe=cyan!60!black}
  \newtcolorbox{note-box}{colback=cyan!5!white,colframe=cyan!60!black}
  \newtcolorbox{tip-box}{colback=green!5!white,colframe=green!60!black}
  \newtcolorbox{warning-box}{colback=orange!5!white,colframe=orange!80!black}
  \newtcolorbox{attention-box}{colback=orange!5!white,colframe=orange!80!black}
  \newtcolorbox{caution-box}{colback=orange!5!white,colframe=orange!80!black}
  \newtcolorbox{error-box}{colback=red!5!white,colframe=red!75!black}
  \newtcolorbox{danger-box}{colback=red!5!white,colframe=red!75!black}
  \newtcolorbox{definition-box}{colback=purple!5!white,colframe=purple!75!black}
  ```
pandoc-latex-environment:
  tcolorbox: [box]
  info-box: [info]
  note-box: [note]
  warning-box: [warning]
  attention-box: [attention]
  caution-box: [caution]
  error-box: [error]
  danger-box: [danger]
  tip-box: [tip]
  definition-box: [definition]
